#!/bin/bash
# Formatting drives
mkfs.fat -F32 /dev/nvme0n1p1 !/dev/sda1 !/dev/vda1 
mkfs.ext4 /dev/nvme0n1p3 !/dev/sda3 !/dev/vda3
mkfs.ext4 /dev/nvme1n1p1 !/dev/sdb1 !/dev/vdb1

# Creating swap partition and setting up swapspace
mkswap /dev/nvme0n1p2 !/dev/sda2 !/dev/vda2
swapon /dev/nvme0n1p2 !/dev/sda2 !/dev/vda2

# Mounting root partition
mount /dev/nvme0n1p3 !/dev/sda3 !/dev/vda3 /mnt

# Creating home directory and mounting partition
mkdir /mnt/home
mount /dev/nvme1n1p1 !/dev/sdb1 !/dev/vdb1 /mnt/home

# Updating pacman
pacman -Syy

# Downloading base packages for install
pacstrap /mnt base base-devel linux linux-firmware nano

# Generating /etc/fstab on new system
genfstab -U /mnt >> /mnt/etc/fstab

# Moving installation files to new system
mv install /mnt

# arch-chroot into new system
arch-chroot /mnt